### ISSUE TITLE
Install pymol also failed on M1 MBP

### ISSUE THREAD

**Issue by SichangHe** [brewsci/homebrew-bio#1554]
## installation attempt

```shell
$ brew install brewsci/bio/pymol
Running `brew update --preinstall`...
==> Downloading https://files.pythonhosted.org/packages/59/04/87fc6708659c2ed3b0b6d4954f270b6e931def707b227c4554f99bd5401e/msgpack-1.0.2.tar.gz
Already downloaded: /Users/sichanghe/Library/Caches/Homebrew/downloads/44ea36b1b860b30e07ef94fa133658ea8af6d988ac4d4ef0dcd412456366c17c--msgpack-1.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/13/ea/c6a302ccdfdcc1ab200bd2b7561e574329055d2974b1fb7939a7aa374da3/mmtf-python-1.1.2.tar.gz
Already downloaded: /Users/sichanghe/Library/Caches/Homebrew/downloads/8184cd2975ddc6f5276f8aca6273b4b0e2e98a69ae60a94e8f087e2bf4f7fbc2--mmtf-python-1.1.2.tar.gz
==> Downloading https://altushost-swe.dl.sourceforge.net/project/pmw/Pmw-2.1.tar.gz
Already downloaded: /Users/sichanghe/Library/Caches/Homebrew/downloads/15507022da5f57d4a0e48ea2eee93a2e42945009c083a6a0e69f9a77aedd67d5--Pmw-2.1.tar.gz
==> Downloading https://github.com/schrodinger/pymol-open-source/archive/v2.5.0.tar.gz
Already downloaded: /Users/sichanghe/Library/Caches/Homebrew/downloads/026e19fbe9447262d569f99bdc16c32df38d2654c09f047ff9e84be5a4655e73--pymol-open-source-2.5.0.tar.gz
==> Installing pymol from brewsci/bio
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/2.5.0/libexec --install-scripts=/opt/homebrew/Cellar/pymol/2.5.0/libexec/bin --single-version-externally-
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/2.5.0/libexec --install-scripts=/opt/homebrew/Cellar/pymol/2.5.0/libexec/bin --single-version-externally-
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/2.5.0/libexec --install-scripts=/opt/homebrew/Cellar/pymol/2.5.0/libexec/bin --single-version-externally-
==> /opt/homebrew/opt/python@3.9/bin/python3 setup.py install --install-scripts=/opt/homebrew/Cellar/pymol/2.5.0/libexec/bin --install-lib=/opt/homebrew/Cellar/pymol/2.5.0/libexec/lib/python3.9/site-packages --glut --use-msgpackc=c+
Last 15 lines from /Users/sichanghe/Library/Logs/Homebrew/pymol/04.python3:
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer4/Menu.cpp -o build/temp.macosx-12-arm64-cpython-39/layer4/Menu.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/MovieScene.cpp -o build/temp.macosx-12-arm64-cpython-39/layer3/MovieScene.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer4/PopUp.cpp -o build/temp.macosx-12-arm64-cpython-39/layer4/PopUp.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer5/PyMOL.cpp -o build/temp.macosx-12-arm64-cpython-39/layer5/PyMOL.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/PlugIOManager.cpp -o build/temp.macosx-12-arm64-cpython-39/layer3/PlugIOManager.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/RingFinder.cpp -o build/temp.macosx-12-arm64-cpython-39/layer3/RingFinder.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
clang++ -I/opt/homebrew/opt/libxml2/include/libxml2 -I/opt/homebrew/opt/freetype/include/freetype2 -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_CTEST -D_PYMOL_OSX -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -IlayerCTest -I/opt/homebrew/lib/python3.9/site-packages/numpy/core/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c -MMD layer3/Seeker.cpp -o build/temp.macosx-12-arm64-cpython-39/layer3/Seeker.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3 -fno-strict-aliasing
error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang++' failed with exit code 1
Exception ignored in: <function Pool.__del__ at 0x101e13e50>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 377, in put
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 405, in _send_bytes
AttributeError: 'NoneType' object has no attribute 'pack'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-bio/issues
```

## background

- I updated Homebrew before trying to install
```shell
$ brew --version
Homebrew 3.4.11
Homebrew/homebrew-core (git revision 39dc86d3ee5; last commit 2022-05-30)
Homebrew/homebrew-cask (git revision da823aa438; last commit 2022-05-30)
```
- This is the second attempt to install pymol, the first attempt is identical except having a lot of `Downloading` at the beginning
- After this method failed, I also tried installing pymol manually, the compilation failed as well, saying `fatal error: 'GL/glew.h' file not found`

## checklist

I will do the checklist as replies to this issue

**Comment by SichangHe** [comment]
## run `brew doctor`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  r
  numpy

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  fish_add_path /opt/homebrew/sbin
```

## run `brew gist-logs pymol`

```shell
$ brew gist-logs pymol
Error: Not Found
```

## run `brew config`

```shell
$ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 39dc86d3ee5b4c1ddd78774e6fae39dedbaf1edb
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.3.1.0.1.1648687083
Xcode: 13.3
Rosetta 2: false
```

**Comment by SichangHe** [comment]
trying to install pymol via the x86 brew, if that work it works for me as well, but this may still be a problem for the script

**Comment by SichangHe** [comment]
I successively installed pymol using x86 Homebrew

**Comment by Luc1100** [comment]
@SichangHe Can you please explain the command you used to install it using x86 Homebrew? I am trying 
`arch -x86_64 /usr/local/homebrew/bin/brew install pymol`
But it gives a different error.

**Comment by YoshitakaMo** [comment]
I've encountered this problem on my M1 Mac, too. Currently, all formulae in this repo must be built from source code because the homebrew-bio's bottle server has been down (?) since May 12. I'll check this issue and try to fix the formula.
I also hope @sjackman will restore the server.

**Comment by SichangHe** [comment]
> @SichangHe Can you please explain the command you used to install it using x86 Homebrew? I am trying
> `arch -x86_64 /usr/local/homebrew/bin/brew install pymol`
> But it gives a different error.

Last year I set up this script in `/usr/local/bin/ibrew` when I switched to the M1 machine (must be from the internet):

```shell
#!/bin/sh
# run brew in Rosetta1
arch -x86_64 /usr/local/bin/brew $@
```

So, when I want to use the x86 brew, I just replace the `brew` command with the `ibrew` command:

```shell
ibrew install brewsci/bio/pymol
```

**Comment by YoshitakaMo** [comment]
@SichangHe @Luc1100 I've fixed the formula. Please update it and try the installation again.

**Comment by Luc1100** [comment]
@YoshitakaMo Thank you so much, got it working again!

**Comment by SichangHe** [comment]
@YoshitakaMo It works now. Nice job!
