### ISSUE TITLE
Tabixpp failed to build on Archlinux

### ISSUE THREAD

**Issue by a-lapin** [brewsci/homebrew-bio#1592]
- [x] Confirmed this is a problem with `brew installing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I've got this error while installing brewsci/bio/tabixpp (which is dependency of brewsci/bio/snippy):
```
**$ brew install tabixpp**
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/manifests/1.1.1
Already downloaded: /home/argive/.cache/Homebrew/downloads/e6bfe99c0d419183f176575fb7493e00f0b6c9a405e2c08a7e6bb87f35d38b6d--tabixpp-1.1.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/blobs/sha256:fef2b7232b66f4851fba14c0c24ff5f4e579077ddf7b516af9b1d694f5264318
Already downloaded: /home/argive/.cache/Homebrew/downloads/a83c1f324e8c53d48f157fbf7d54c1395688c72737e0e144337f4fd5eb6c9126--tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
==> Installing tabixpp from brewsci/bio
==> Pouring tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:682:in `normalize_note_segment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:659:in `block in normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:955:in `block in phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each_with_index'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:653:in `normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:638:in `rewrite_sections_library'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:475:in `rewrite_sections'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:88:in `save!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:191:in `save'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:167:in `save_using_patchelf_rb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `patch!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `change_rpath'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:15:in `block (2 levels) in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:341:in `ensure_writable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:14:in `block in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:132:in `replace_placeholders_with_locations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1226:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:425:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
**$ brew update**
Updated 1 tap (homebrew/core).
**$ brew install tabixpp**
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/manifests/1.1.1
Already downloaded: /home/argive/.cache/Homebrew/downloads/e6bfe99c0d419183f176575fb7493e00f0b6c9a405e2c08a7e6bb87f35d38b6d--tabixpp-1.1.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/blobs/sha256:fef2b7232b66f4851fba14c0c24ff5f4e579077ddf7b516af9b1d694f5264318
Already downloaded: /home/argive/.cache/Homebrew/downloads/a83c1f324e8c53d48f157fbf7d54c1395688c72737e0e144337f4fd5eb6c9126--tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
==> Installing tabixpp from brewsci/bio
==> Pouring tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:682:in `normalize_note_segment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:659:in `block in normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:955:in `block in phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each_with_index'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:653:in `normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:638:in `rewrite_sections_library'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:475:in `rewrite_sections'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:88:in `save!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:191:in `save'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:167:in `save_using_patchelf_rb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `patch!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `change_rpath'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:15:in `block (2 levels) in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:341:in `ensure_writable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:14:in `block in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:132:in `replace_placeholders_with_locations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1226:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:425:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

``` 

I tried to install tabixpp on Arch linux (kernel 6.0.9) and got the same error on Ubuntu 22.04.
Here is my brew doctor & brew config output: 

```
$ brew doctor
Your system is ready to brew.
**$ brew config**
HOMEBREW_VERSION: 3.6.12-20-g9c88c39
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c88c39baead6bbc40b12ab1eae9b63bcb5a8042
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d6e1fac078582fa3f1619c4792d58bb31f0dd5d3
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.38.1 => /bin/git
Curl: 7.86.0 => /bin/curl
Kernel: Linux 6.0.9-zen1-1-zen x86_64 GNU/Linux
OS: Arch Linux
Host glibc: 2.36
/usr/bin/gcc: 12.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 12.2.0
xorg: N/A
```

**Comment by YoshitakaMo** [comment]
Now I've updated the tabixpp formula. Please test the one.
