### ISSUE TITLE
brew install viennarna error

### ISSUE THREAD

**Issue by petervangalen** [brewsci/homebrew-bio#1637]
I tried to install viennarna using Homebrew 4.1.6 on a Mac M1 Max with Ventura 13.5.1 (22G90).

When executing `brew install viennarna`, I got the following error at the `make` stage:

```
Last 15 lines from /Users/vangalen/Library/Logs/Homebrew/viennarna/02.make:
  File "<string>", line 1, in <module>
  File "/private/tmp/viennarna-20230823-53253-13ovwhz/ViennaRNA-2.4.17/interfaces/Python3/RNA/__init__.py", line 11, in <module>
    from . import _RNA
ImportError: cannot import name '_RNA' from partially initialized module 'RNA' (most likely due to a circular import) (/private/tmp/viennarna-20230823-53253-13ovwhz/ViennaRNA-2.4.17/interfaces/Python3/RNA/__init__.py)
make[3]: *** [RNA/__pycache__/__init__.cpython-311.pyc] Error 1
make[3]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/viennarna-20230823-53253-13ovwhz/ViennaRNA-2.4.17/interfaces/Python3/RNA/__init__.py", line 11, in <module>
    from . import _RNA
ImportError: cannot import name '_RNA' from partially initialized module 'RNA' (most likely due to a circular import) (/private/tmp/viennarna-20230823-53253-13ovwhz/ViennaRNA-2.4.17/interfaces/Python3/RNA/__init__.py)
make[3]: *** [RNA/__pycache__/__init__.cpython-311.opt-1.pyc] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

The logs are here:
https://gist.github.com/petervangalen/3fade21a599c70f418d67d3b8cc2b8c1

**update**
I retried `brew install viennarna` after running `export PATH="/opt/homebrew/bin:$PATH"` but got the same error

**Comment by retospect** [comment]
Same here, but it works for 2.5.1.
Download the old source package from the bottom of https://www.tbi.univie.ac.at/RNA/#source_code_packages
