### ISSUE TITLE
beast2: missing beauti templates

### ISSUE THREAD

**Issue by gaberoo** [brewsci/homebrew-bio#660]
`beauti-2` doesn't launch from the BEAST2 installation because of missing templates.
```
 ❯ beauti-2
[java, -Djava.library.path=/usr/local/Cellar/beast2/2.5.0/libexec/lib, -cp, ::/usr/local/opt/beast2/share/beast2/BEAST/lib/beast.src.jar:/usr/local/opt/beast2/share/beast2/BEAST/lib/beast.jar, beast.app.beauti.Beauti, -capture]
BeastMain found in /usr/local/Cellar/beast2/2.5.0/share/beast2/BEAST/lib/beast.jar
BeastMain found in /usr/local/Cellar/beast2/2.5.0/share/beast2/BEAST/lib/beast.jar
Warning: corrupt classpath entry:
Warning: corrupt classpath entry:
ch.randelshofer.quaqua.QuaquaLookAndFeel
Loading template /Users/gaberoo/./templates/templates/Standard.xml
java.io.FileNotFoundException: /Users/gaberoo/./templates/templates/Standard.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at beast.app.beauti.BeautiDoc.load(Unknown Source)
	at beast.app.beauti.BeautiDoc.load(Unknown Source)
	at beast.app.beauti.BeautiDoc.processTemplate(Unknown Source)
	at beast.app.beauti.BeautiDoc.mergeSequences(Unknown Source)
	at beast.app.beauti.BeautiDoc.initialize(Unknown Source)
	at beast.app.beauti.BeautiDoc.parseArgs(Unknown Source)
	at beast.app.beauti.Beauti.main2(Unknown Source)
	at beast.app.beauti.Beauti.main(Unknown Source)
```

There are multiple steps to resolving this:
1. include the `templates` folder into `pkgshare`
2. make sure the paths are correctly passed to `beauti`

**Comment by AlesBucek** [comment]
(still unresolved)

**Comment by sjackman** [comment]
I'd be happy to merge a PR resolving this issue.
